---
title: "TokyoR#42 テキスト (Rで学ぶデータマイニングⅠ 第１８章)"
output: html_document
---

```{r}
library(ggplot2)
library(scales)
```

## 交通事故死者数データ

### データ作成
```{r}
death <- data.frame(
  year=7:17,
  shisha=c(10679,9942,9640,9211,9006,9066,8747,8326,7702,7358,6871))
```

### 事故発生後24時間いないの交通事故者数1
```{r warning=FALSE,fig.width=12,fig.height=8}

ggplot(subset(death, year>=13), aes(x=year, y=shisha-6000)) +
  geom_bar(stat="identity", col="black", fill="grey") +
  scale_y_continuous(
    breaks = seq(0, 4000, by = 1000),
    labels = comma(seq(6000,10000, by=1000))
  ) +
  xlab("") +
  ylab("人数") +
  ggtitle("事故発生後24時間いないの交通事故者数") +
  theme_bw(base_family="Osaka")

```

### 事故発生後24時間いないの交通事故者数2
```{r warning=FALSE,fig.width=12,fig.height=8}

ggplot(subset(death, year>=13), aes(x=year, y=shisha)) +
  geom_bar(stat="identity", col="black", fill="grey") +
  scale_y_continuous(label=comma) +
  xlab("") +
  ylab("人数") +
  ggtitle("事故発生後24時間いないの交通事故者数") +
  theme_bw(base_family="Osaka")

```


### 事故発生後24時間いないの交通事故者数3
```{r warning=FALSE,fig.width=12,fig.height=8}
ggplot(death, aes(x=year, y=shisha)) +
  geom_bar(col="black", fill="grey", stat="identity") +
  scale_y_continuous(label=comma) +
  xlab("") +
  ylab("人数") +
  ggtitle("事故発生後24時間いないの交通事故者数") +
  theme_bw(base_family="Osaka")
```

### 事故発生後24時間いないの交通事故者数4
```{r warning=FALSE,fig.width=12,fig.height=8}
ggplot(death, aes(x=year, y=shisha)) +
  geom_line() +
  geom_point(shape=1, size=2) +
  scale_y_continuous(label=comma) +
  xlab("") +
  ylab("人数") +
  ggtitle("事故発生後24時間いないの交通事故者数") +
  theme_bw(base_family="Osaka")
```


### 事故発生後24時間いないの交通事故者数5
```{r warning=FALSE,fig.width=12,fig.height=4}
ggplot(death, aes(x=year, y=shisha)) +
  geom_bar(col="black", fill="grey", stat="identity") +
  scale_y_continuous(label=comma) +
  xlab("") +
  ylab("") +
  ggtitle("事故発生後24時間いないの交通事故者数") +
  theme_bw(base_family="Osaka")
```



### 飲酒有無別交通事故死亡者数 推移
```{r warning=FALSE,fig.width=12,fig.height=8}
library(reshape2)

death2 <- read.csv("death2.csv", fileEncoding="shift_jis")
death2_melt <- melt(death2, id.vars = "year")

ggplot(death2_melt, aes(x=as.factor(year), y=value, col=variable, shape=variable, group=variable)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(label=comma, limits=c(0,NA)) +
  xlab("") +
  ylab("人数") +
  ggtitle("飲酒有無別交通事故死亡者数") +
  theme_bw(base_family="Osaka")
```


### 飲酒有交通事故死亡者数 推移
```{r warning=FALSE,fig.width=12,fig.height=8}

ggplot(subset(death2_melt, variable=="飲酒あり.第１当事者."), aes(x=as.factor(year), y=value, col=variable, shape=variable, group=variable)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(label=comma, limits=c(0,NA)) +
  xlab("") +
  ylab("人数") +
  ggtitle("飲酒有交通事故死亡者数") +
  theme_bw(base_family="Osaka")
```



### 飲酒有無別交通事故数 推移
```{r warning=FALSE,fig.width=12,fig.height=8}
jiko <- read.csv("inshu_jiko.csv", fileEncoding="shift_jis")
jiko_melt <- melt(jiko, id.vars = "year")

ggplot(jiko_melt, aes(x=as.factor(year), y=value, col=variable, shape=variable, group=variable)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(label=comma, limits=c(0,NA)) +
  xlab("") +
  ylab("事故数") +
  ggtitle("飲酒有無別交通事故数") +
  theme_bw(base_family="Osaka")
```


### 飲酒有交通事故数 推移
```{r warning=FALSE,fig.width=12,fig.height=8}

ggplot(subset(jiko_melt, variable=="飲酒あり"), aes(x=as.factor(year), y=value, col=variable, shape=variable, group=variable)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(label=comma, limits=c(0,NA)) +
  xlab("") +
  ylab("人数") +
  ggtitle("飲酒有交通事故数") +
  theme_bw(base_family="Osaka")
```

### 飲酒有無別死亡事故率 推移
```{r warning=FALSE,fig.width=12,fig.height=8}
death_rate <- read.csv("death_rate.csv", fileEncoding="shift_jis")
death_rate_melt <- melt(death_rate, id.vars = "year")

ggplot(death_rate_melt, aes(x=as.factor(year), y=value, col=variable, shape=variable, group=variable)) +
  geom_line() +
  geom_point() +
  scale_y_continuous(label=comma, limits=c(0,NA)) +
  xlab("") +
  ylab("死亡事故率") +
  ggtitle("飲酒有無別死亡事故率（%）") +
  theme_bw(base_family="Osaka")
```


```{r}
death.rate <- data.frame(
  year=8:17,
  rate=(death$shisha[-1] - death$shisha[-nrow(death)]) / death$shisha[-1]
  )

```


```{r warning=FALSE,fig.width=12,fig.height=8}
ggplot(death.rate, aes(x=year, y=rate)) +
  geom_line() +
  geom_point(shape=1, size=2) +
  geom_abline(intercept=0, slope=0, lty=2) +
  ggtitle("事故発生後24時間いないの交通事故者数の増減率") +
  theme_bw(base_family="Osaka")
```


```{r}
death.rate$rate.scaled <- scale(death.rate$rate)
```

```{r warning=FALSE,fig.width=12,fig.height=8}
ggplot(death.rate, aes(x=year, y=rate.scaled)) +
  geom_line() +
  geom_point(shape=1, size=2) +
  geom_abline(intercept=0, slope=0, lty=2) +
  geom_abline(intercept=1.96, slope=0, lty=2) +
  geom_abline(intercept=-1.96, slope=0, lty=2) +
  ylim(-2.2, 2.2) +
  ggtitle("基準化された増減率") +
  theme_bw(base_family="Osaka")
```


```{r}
death.rate$gmean <- 
  exp(sum(log(1+death.rate$rate))/length(death.rate$rate))

death.rate$rate.gscaled <- 
  (death.rate$rate+1 - death.rate$gmean) / sqrt(sum((death.rate$rate+1 - death.rate$gmean)^2)/(nrow(death.rate)-1))

```

```{r warning=FALSE,fig.width=12,fig.height=8}
ggplot(death.rate, aes(x=year, y=rate.gscaled)) +
  geom_line() +
  geom_point(shape=1, size=2) +
  geom_abline(intercept=0, slope=0, lty=2) +
  geom_abline(intercept=1.96, slope=0, lty=2) +
  geom_abline(intercept=-1.96, slope=0, lty=2) +
  ylim(-2.2, 2.2) +
  ggtitle("基準化された増減率") +
  theme_bw(base_family="Osaka")
```

## 漢字問題データ
大学生は漢字が苦手


|グループ | 検定の合格率 |
|---------|--------------|
| 中学1年生 | 78.5%      |
| 高校1年生 | 59.0%      |
| 大学1年生 | 39.8%      |
| 上場企業新入社員 | 60.7% |

```{r}
kanji <- data.frame(
  group=factor(c("中学1","高校1","大学1","新入社員"),
               levels=c("中学1","高校1","大学1","新入社員")),
  rate=c(78.5, 59.0, 39.8, 60.7))
```


```{r warning=FALSE,fig.width=12, fig.height=8}
ggplot(kanji, aes(x=group, y=rate)) +
  geom_bar(col="black",fill="grey",stat="identity") +
  ylim(0,100) +
  xlab("グループ") +
  ylab("検定の合格率") +
  theme_bw(base_family="Osaka")
```


## インフルエンザワクチンの有効率データ
インフルエンザワクチン：昨冬の効果 有効率27%

```{r}
flu <- data.frame(
  year=c(13, 14, 15, 16),
  vac=c(0.3, 1.9, 1.7, 4.8),
  n.vac=c(1.2, 5.9, 2.4, 6.6))

flu <- transform(flu, eff=round( (n.vac-vac)/n.vac*100, 1))
flu
```

```{r warning=FALSE, fig.width=8,fig.height=6}
ggplot(flu, aes(x=year, y=eff)) +
  geom_line() +
  geom_point() +
  xlab("有効率") +
  ylab("") +
  ylim(0,80) +
  theme_bw(base_family="Osaka")
```

```{r warning=FALSE, fig.width=8,fig.height=6}
ggplot(flu, aes(x=year, y=eff)) +
  geom_bar(col="black",fill="grey",stat="identity") +
  xlab("有効率") +
  ylab("") +
  ylim(0,80) +
  theme_bw(base_family="Osaka")
```


```{r}
flu2 <- data.frame(
  vac=c(14364-696, 696, 14364),
  n.vac=c(3101-206, 206, 3101))
row.names(flu2) <- c("fine","sick","sum")
flu2
```

```{r}
flu2.ratio <- flu2["sick",] / flu2["sum",] * 100
row.names(flu2.ratio) <- c("ratio")
flu2.ratio
```


```{r}
prop.test(as.numeric(flu2["sick",]), 
          as.numeric(flu2["sum",]))
```

```{r}
prop.test(as.numeric(flu2["sick",]), 
          as.numeric(flu2["sum",]),
          p=c(0.05, 0.05))
```


